Page({
  data: {
    trainingStages: [
      {
        title: "阶段一：认识和稳定情绪",
        subtitle: "先看见情绪，再让身体慢下来",
        tasks: [
          {
            id: "emotion_education",
            title: "情绪教育",
            subtitle: "理解情绪，不急着压下去",
            stage: "阶段一",
            duration: "5 分钟",
            scenario: "不知道孩子为什么突然激动时",
            tag: "新手",
            tags: ["emotion_awareness"],
            tagsText: "emotion_awareness",
          },
          {
            id: "emotion_awareness",
            title: "情绪觉察",
            subtitle: "看见自己的情绪变化",
            stage: "阶段一",
            duration: "3-5 分钟",
            scenario: "发现自己语速变快、胸口发紧时",
            tag: "推荐",
            tags: ["emotion_awareness", "high_emotion_intensity"],
            tagsText: "emotion_awareness,high_emotion_intensity",
          },
          {
            id: "body_regulation",
            title: "身体调节",
            subtitle: "通过呼吸和放松稳定身体",
            stage: "阶段一",
            duration: "5-8 分钟",
            scenario: "准备提高音量或身体紧绷时",
            tag: "新手",
            tags: ["high_emotion_intensity", "emotional_behavior"],
            tagsText: "high_emotion_intensity,emotional_behavior",
          },
          {
            id: "pause_training",
            title: "暂停训练",
            subtitle: "在冲突前先停一停",
            stage: "阶段一",
            duration: "3-5 分钟",
            scenario: "亲子冲突前、催促前",
            tag: "推荐",
            tags: ["high_demand_language", "emotional_behavior"],
            tagsText: "high_demand_language,emotional_behavior",
          },
        ],
      },
      {
        title: "阶段二：改变想法和行为",
        subtitle: "从自动反应转向更有帮助的回应",
        tasks: [
          {
            id: "cognitive_adjustment",
            title: "认知调整",
            subtitle: "换一个角度理解事件",
            stage: "阶段二",
            duration: "5-8 分钟",
            scenario: "觉得孩子就是故意拖延时",
            tag: "进阶",
            tags: ["negative_attribution", "catastrophic_prediction"],
            tagsText: "negative_attribution,catastrophic_prediction",
          },
          {
            id: "alternative_thought",
            title: "替代想法",
            subtitle: "找到更有帮助的想法",
            stage: "阶段二",
            duration: "5 分钟",
            scenario: "脑中反复出现责备或担心时",
            tag: "进阶",
            tags: ["negative_attribution", "cognitive_flexibility"],
            tagsText: "negative_attribution,cognitive_flexibility",
          },
          {
            id: "communication_expression",
            title: "沟通表达",
            subtitle: "把感受说清楚",
            stage: "阶段二",
            duration: "5-10 分钟",
            scenario: "想表达要求但担心变成指责时",
            tag: "练习",
            tags: ["high_demand_language", "judgmental_language"],
            tagsText: "high_demand_language,judgmental_language",
          },
        ],
      },
      {
        title: "阶段三：改善亲子关系",
        subtitle: "先连接，再讨论问题",
        tasks: [
          {
            id: "nonjudgmental_company",
            title: "非评判陪伴",
            subtitle: "先接住孩子的情绪",
            stage: "阶段三",
            duration: "5-10 分钟",
            scenario: "孩子委屈、生气或不愿说话时",
            tag: "推荐",
            tags: ["judgmental_language", "parent_child_conflict"],
            tagsText: "judgmental_language,parent_child_conflict",
          },
          {
            id: "relationship_repair",
            title: "关系修复",
            subtitle: "冲突后重新连接",
            stage: "阶段三",
            duration: "8-10 分钟",
            scenario: "刚发生争吵或冷处理后",
            tag: "进阶",
            tags: ["parent_child_conflict", "emotional_behavior"],
            tagsText: "parent_child_conflict,emotional_behavior",
          },
          {
            id: "positive_interaction",
            title: "积极互动",
            subtitle: "增加家庭中的正向时刻",
            stage: "阶段三",
            duration: "5 分钟",
            scenario: "想减少指责、增加合作时",
            tag: "练习",
            tags: ["behavior_substitution", "nonjudgmental_response"],
            tagsText: "behavior_substitution,nonjudgmental_response",
          },
        ],
      },
    ],
  },

  openTrainingCard(event) {
    const id = event.currentTarget.dataset.id || event.target.dataset.id || "";
    wx.navigateTo({
      url: `/pages/task-detail/index?id=${encodeURIComponent(id)}`,
    });
  },
});
