"""Generate Web and mini-program relationship status helpers from one JSON contract."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "shared" / "contracts" / "relationship-ui.json"
MINIPROGRAM_OUTPUT = ROOT / "apps" / "miniprogram" / "utils" / "relationshipStatus.generated.js"
WEB_OUTPUT = ROOT / "apps" / "web" / "src" / "generated" / "relationshipStatus.generated.ts"


def generate_miniprogram(contract: dict) -> str:
    payload = json.dumps(contract, ensure_ascii=False, indent=2)
    return (
        "// Generated by backend/scripts/generate_relationship_ui_contract.py.\n"
        f"const CONTRACT = {payload};\n\n"
        "function reportStatus(status) {\n"
        "  return CONTRACT.report_statuses[status] || CONTRACT.fallback;\n"
        "}\n\n"
        "function reportStatusLabel(status) {\n"
        "  return reportStatus(status).label;\n"
        "}\n\n"
        "function visualizationState(state) {\n"
        "  return CONTRACT.visualization_states[state] || CONTRACT.visualization_states.error;\n"
        "}\n\n"
        "module.exports = { CONTRACT, reportStatus, reportStatusLabel, visualizationState };\n"
    )


def generate_web(contract: dict) -> str:
    statuses = json.dumps(contract["report_statuses"], ensure_ascii=False, indent=2)
    visualization_states = json.dumps(contract["visualization_states"], ensure_ascii=False, indent=2)
    fallback = json.dumps(contract["fallback"], ensure_ascii=False)
    return (
        "// Generated by backend/scripts/generate_relationship_ui_contract.py.\n"
        f"export const RELATIONSHIP_REPORT_STATUSES = {statuses} as const;\n"
        f"export const RELATIONSHIP_STATUS_FALLBACK = {fallback} as const;\n"
        f"export const VISUALIZATION_STATES = {visualization_states} as const;\n"
        "export type RelationshipReportStatus = keyof typeof RELATIONSHIP_REPORT_STATUSES;\n"
        "export type VisualizationState = keyof typeof VISUALIZATION_STATES;\n\n"
        "export function relationshipReportStatus(status: string) {\n"
        "  return RELATIONSHIP_REPORT_STATUSES[status as RelationshipReportStatus] || RELATIONSHIP_STATUS_FALLBACK;\n"
        "}\n\n"
        "export function visualizationState(state: VisualizationState) {\n"
        "  return VISUALIZATION_STATES[state];\n"
        "}\n"
    )


def outputs() -> dict[Path, str]:
    contract = json.loads(SOURCE.read_text(encoding="utf-8"))
    return {
        MINIPROGRAM_OUTPUT: generate_miniprogram(contract),
        WEB_OUTPUT: generate_web(contract),
    }


def main() -> None:
    for path, content in outputs().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"generated {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
