"""Generate relationship-pilot TypeScript types from the shared JSON Schema."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SCHEMA_PATH = ROOT / "shared" / "contracts" / "relationship-pilot.schema.json"
OUTPUT_PATH = ROOT / "shared" / "types" / "relationship-pilot.generated.ts"


def _literal(value) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    return str(value)


def _render(schema: dict, indent: int = 0) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "enum" in schema:
        return " | ".join(_literal(value) for value in schema["enum"])
    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(_render({**schema, "type": item}, indent) for item in schema_type)
    if schema_type == "string":
        return "string"
    if schema_type in {"number", "integer"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        return f"Array<{_render(schema.get('items', {}), indent)}>"
    if schema_type == "object" or "properties" in schema or "additionalProperties" in schema:
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        lines = ["{"]
        for name, child in properties.items():
            optional = "" if name in required else "?"
            lines.append(f"{' ' * (indent + 2)}{name}{optional}: {_render(child, indent + 2)};")
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            value_type = _render(additional, indent + 2)
            lines.append(f"{' ' * (indent + 2)}[key: string]: {value_type} | undefined;")
        elif additional is True:
            lines.append(f"{' ' * (indent + 2)}[key: string]: unknown;")
        lines.append(f"{' ' * indent}}}")
        return "\n".join(lines)
    return "unknown"


def generate(schema_path: Path = SCHEMA_PATH) -> str:
    schema = json.loads(schema_path.read_text(encoding="utf-8"))
    definitions = schema.get("$defs") or {}
    if not definitions:
        raise ValueError("relationship-pilot schema must define $defs")
    chunks = [
        "// Generated by backend/scripts/generate_relationship_contract_types.py.",
        "// Do not edit by hand; update shared/contracts/relationship-pilot.schema.json.",
        "",
    ]
    for name, definition in definitions.items():
        chunks.append(f"export type {name} = {_render(definition)};")
        chunks.append("")
    return "\n".join(chunks).rstrip() + "\n"


def main() -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(generate(), encoding="utf-8")
    print(f"generated {OUTPUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
