// Generated by backend/scripts/generate_relationship_contract_types.py.
// Do not edit by hand; update shared/contracts/relationship-pilot.schema.json.

export type RelationshipDimension = {
  key?: string;
  code?: string;
  label?: string;
  score?: number;
  item_count?: number;
  [key: string]: unknown;
};

export type RadarFeature = {
  code: string;
  z_score: number;
};

export type RelationshipPilotTask = {
  id: string;
  enrollment_id: string;
  user_id: string;
  task_type: "relationship_drawing" | "sentence_completion";
  narration?: string | null;
  drawing_data?: {
    [key: string]: unknown;
  };
  answers?: {
    [key: string]: string | undefined;
  };
  material_consent: 0 | 1;
  risk_level: "low" | "medium" | "high";
  review_status: string;
  created_at: string;
  [key: string]: unknown;
};

export type RelationshipPilotEnrollment = {
  id: string;
  user_id: string;
  nickname?: string | null;
  assessment_result_id: string;
  worksheet_id: string;
  profile_model_id?: string | null;
  profile_cluster_id?: number | null;
  assigned_researcher_id?: string | null;
  status: string;
  review_status: string;
  dimensions: Array<RelationshipDimension>;
  radar_features: Array<RadarFeature>;
  profile: {
    profile_name?: string;
    profile_description?: string;
    confidence?: number;
    interpretation_status?: "usable" | "low_confidence" | "outlier";
    suggested_assessment_questions?: Array<string>;
    recommended_project_tasks?: Array<string>;
    boundary_notice?: string;
    [key: string]: unknown;
  };
  tasks_count?: number;
  report_id?: string | null;
  report_status?: "pending_review" | "ready" | "confirmed" | "sent" | "updated" | null;
  notes_count?: number;
  tasks?: Array<RelationshipPilotTask>;
  reports?: Array<{
    id: string;
    status: string;
    version: string;
    created_at: string;
    confirmed_at?: string | null;
  }>;
  research_notes?: Array<{
    id: string;
    note: string;
    researcher_id: string;
    created_at: string;
  }>;
  created_at: string;
  [key: string]: unknown;
};

export type FourLayerProfile = {
  basic: {
    stage_name?: string;
    description?: string;
    dimensions?: Array<RelationshipDimension>;
    [key: string]: unknown;
  };
  tension: {
    clues: Array<string>;
    status?: string;
    [key: string]: unknown;
  };
  mechanism: {
    hypotheses: Array<string>;
    status?: string;
    [key: string]: unknown;
  };
  dynamic: {
    rounds_count: number;
    changes: Array<{
      [key: string]: unknown;
    }>;
    description?: string;
    [key: string]: unknown;
  };
};

export type HypothesisFeedback = {
  hypothesis_index: number;
  response: "matches" | "does_not_match" | "uncertain";
  updated_at: string;
};

export type RelationshipScreeningReport = {
  id: string;
  enrollment_id: string;
  user_id: string;
  status: "pending_review" | "ready" | "confirmed" | "sent" | "updated";
  version: string;
  sent_at?: string | null;
  hypothesis_feedback?: Array<HypothesisFeedback>;
  report: {
    title: string;
    profile_name: string;
    profile_description: string;
    confidence?: number | null;
    interpretation_status?: "usable" | "low_confidence" | "outlier" | null;
    personalized_interpretation: string;
    dimensions: Array<RelationshipDimension>;
    radar_features: Array<RadarFeature>;
    suggested_assessment_questions: Array<string>;
    recommended_project_tasks: Array<string>;
    four_layer_profile?: FourLayerProfile;
    boundary_notice: string;
    generated_at: string;
    version: string;
  };
  created_at: string;
  [key: string]: unknown;
};

export type RelationshipGrowth = {
  user_id: string;
  curves: {
    [key: string]: Array<{
      round: number;
      value: number;
      created_at: string;
    }> | undefined;
  };
  timeline: Array<{
    id: string;
    type: "assessment" | "project_task" | "weekly_supplement" | "key_event" | "report" | "researcher_feedback";
    title: string;
    created_at: string;
    summary: string;
    risk_level?: "low" | "medium" | "high";
  }>;
  growth_report: {
    [key: string]: unknown;
  };
};
